 
version: '3.8'
services:
  gymbackend:
    image: hritik2345/gym-management:latest
    ports:
      - "80:8000"
    restart: always
    env_file:
      - .env  # This tells Docker to look for a file named .env in the same folder